<a href="https://colab.research.google.com/github/EnGineerAI4547/School_Projects/blob/main/Eric_Gonzalez_assignment2_cap5768.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Assignment 2**

**Eric Gonzalez**

**CAP 5768**





**Q1. Why do we use extend function in Python? Can we use extend function with set and tuple?**




*   *We use the extend function in pyton to quickly add elements or entire lists to another list*.
*   *We can use the extend function with sets although with the caveat that you will only add unique elements to the set as that is one of the properties of a set.*
*   *In regards to tuples, extend python function cannot be used because tuples are immutable.*











**Q2. What is the difference between insert and append methods in Python?**



*   *the difference between insert and append methods in python are append always adds elements to the end of the iterable whereas insert requires an index and will insert the element according to the index given. Only if no index is given will the insert method add the element to the last index of the iterable.*  







**Q3. What is the difference between view and copy functions?**



*   *The difference between the view and copy functions is that a function created using the view function references the original object's data buffer while the object created using copy function references a copy of the data housed in it's own data buffer. Thus with the view any changes made to the original or to the view will change the other since the changes are made to the source which is the pointed to data buffer. This is different with the copy function which when changed will not change the original data at all.*  




**Q4. Why do we use stack and how hstack is different from vstack?**



*   *We use stack function to combine two or more arrays along a new axis. And hstack and vstack differ in which axis they stack or combine the data along. In an array there is a vertical and horizontal axis. The hstack function stacks arrays along the horizontal axis and vstack along the vertical axis.*




In [3]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

stacked_1 = np.hstack([arr1, arr2])

print(f"Hstack = {stacked_1}")


arr3 = np.array([7, 8, 9])
arr4 = np.array([10, 11, 12])

stacked_2 = np.vstack([arr3, arr4])

print(f"Vstack = {stacked_2}")

Hstack = [1 2 3 4 5 6]
Vstack = [[ 7  8  9]
 [10 11 12]]


**Q5. Read the data.csv using numpy.**


In [18]:
import numpy as np


data=np.genfromtxt("data.csv",delimiter=",", names=True, dtype=None, encoding='utf-8')

print(data)
column_names = data.dtype.names
print("------------------------------------------------------------------------\n")
print(f"\nColumn names= {column_names}")


[( 60, 110, 130,  409.1) ( 60, 117, 145,  479. ) ( 60, 103, 135,  340. )
 ( 45, 109, 175,  282.4) ( 45, 117, 148,  406. ) ( 60, 102, 127,  300. )
 ( 60, 110, 136,  374. ) ( 45, 104, 134,  253.3) ( 30, 109, 133,  195.1)
 ( 60,  98, 124,  269. ) ( 60, 103, 147,  329.3) ( 60, 100, 120,  250.7)
 ( 60, 106, 128,  345.3) ( 60, 104, 132,  379.3) ( 60,  98, 123,  275. )
 ( 60,  98, 120,  215.2) ( 60, 100, 120,  300. ) ( 45,  90, 112,    nan)
 ( 60, 103, 123,  323. ) ( 45,  97, 125,  243. ) ( 60, 108, 131,  364.2)
 ( 45,  -1, 119,  282. ) ( 60, 130, 101,  300. ) ( 45, 105, 132,  246. )
 ( 60, 102, 126,  334.5) ( 60, 100, 120,  250. ) ( 60,  92, 118,  241. )
 ( 60, 103, 132,    nan) ( 60, 100, 132,  280. ) ( 60, 102, 129,  380.3)
 ( 60,  92, 115,  243. ) ( 45,  90, 112,  180.1) ( 60, 101, 124,  299. )
 ( 60,  93, 113,  223. ) ( 60, 107, 136,  361. ) ( 60, 114, 140,  415. )
 ( 60, 102, 127,  300. ) ( 60, 100, 120,  300. ) ( 60, 100, 120,  300. )
 ( 45, 104, 129,  266. ) ( 45,  90, 112,  180.1) ( 

**Q6: Create a numpy array by selecting a pulse column from the dataset and naming it "Pulse."**


In [19]:
pulse_data=data["Pulse"]

print(f"This is the pulse data: {pulse_data}")

This is the pulse data: [110 117 103 109 117 102 110 104 109  98 103 100 106 104  98  98 100  90
 103  97 108  -1 130 105 102 100  92 103 100 102  92  90 101  93 107 114
 102 100 100 104  90  -1 100 111 111  99 109 111 108 111 107 123 106 118
 136 121 118 115 153 123 108 110 109 118 110  90 105 107 106 108  97 109
 100  97 114  98 105 110 100 100 159  -1 103 100 100 151 102 100 129  83
 101 107  90  80 150 151  95 152 109  93  95  90  90  90  92  93  90  90
  90 137 102 107 124 100 108 108 116  97 105 103 112  -1 119 107 111  98
  97 109  99 114 104 107 103 106 103 136 117 115 113 141 108  97 100 122
 136 106 107 112 103 110 106 109 109 150  -1 111  97 100 114  80  85  90
  95 100 105 110 115 120 125]


**Q7: Create a numpy array by selecting the Maxpulse column from the dataset and naming it "MaxPulse."**

In [20]:
maxpulse_data=data["Maxpulse"]

print(f"This is the pulse data: {maxpulse_data}")

This is the pulse data: [130 145 135 175 148 127 136 134 133 124 147 120 128 132 123 120 120 112
 123 125 131 119 101 132 126 120 118 132 132 129 115 112 124 113 136 140
 127 120 120 129 112 126 122 138 131 119 153 136 129 139 136 146 130 151
 175 146 121 144 172 152 160 137 135 141 130 130 135 130 136 143 129 153
 127  -1 146 125 134 141 130 131 182 169 139 130 120 170 136 157  -1 107
 127 137 107 100 171 168 128 168 131 124 112 110 100 100 108 128 120 120
 120 184 124 124 139 120 131 151 141 122 125 124 137 120 169 127 151 122
 124 127 125 151 134 138 133 132  -1 156 143 137 138 162 135 127 120 149
 170 126 136 146 127 150 134 129 138 167 128 151 131 120 150 120 120 130
  -1 140 140 145 145 150 150]


**Q8: Add Pulse and MaxPulsey using np.sum() and np.add().**

In [24]:


# Method 1: Using np.sum()
sum_pulse_maxpulse = np.sum([data['Pulse'], data['Maxpulse']], axis=0)

print(f"This is the numpy sum of Maxpulse and Pulse= {sum_pulse_maxpulse}")

# Method 2: Using np.add()
add_pulse_maxpulse = np.add(data['Pulse'], data['Maxpulse'])

print(f"This is the numpy addition of Maxpulse and Pulse= {add_pulse_maxpulse}")

This is the numpy sum of Maxpulse and Pulse= [240 262 238 284 265 229 246 238 242 222 250 220 234 236 221 218 220 202
 226 222 239 118 231 237 228 220 210 235 232 231 207 202 225 206 243 254
 229 220 220 233 202 125 222 249 242 218 262 247 237 250 243 269 236 269
 311 267 239 259 325 275 268 247 244 259 240 220 240 237 242 251 226 262
 227  96 260 223 239 251 230 231 341 168 242 230 220 321 238 257 128 190
 228 244 197 180 321 319 223 320 240 217 207 200 190 190 200 221 210 210
 210 321 226 231 263 220 239 259 257 219 230 227 249 119 288 234 262 220
 221 236 224 265 238 245 236 238 102 292 260 252 251 303 243 224 220 271
 306 232 243 258 230 260 240 238 247 317 127 262 228 220 264 200 205 220
  94 240 245 255 260 270 275]
This is the numpy addition of Maxpulse and Pulse= [240 262 238 284 265 229 246 238 242 222 250 220 234 236 221 218 220 202
 226 222 239 118 231 237 228 220 210 235 232 231 207 202 225 206 243 254
 229 220 220 233 202 125 222 249 242 218 262 247 237 250 243 269 236 269

**Question 8 continued: What is the difference between summation and addition?**



*   *As you can see there is no difference in the results or sums of the two arrays although the process by which the additions happen do differ. The main difference is that the np.sum() function is typically used for summing elements on a given axis while np.add() is used for summing entire arrays in an element by element fashion.*  




**Q9: Find and print all the indexes where Pulse = 100.**

In [29]:

indexes_100=np.where(data["Pulse"]==100)
print(indexes_100)

(array([ 11,  16,  25,  28,  37,  38,  42,  72,  78,  79,  83,  84,  87,
       113, 142, 157, 163]),)


**Q10: Filter rows where Pulse is greater than 130 and Calories are greater than 400**.

In [33]:
indexes_130_400=np.where((data["Pulse"]>130) & (data["Calories"]>400))
print(indexes_130_400)

(array([109, 144]),)


**Q11: Create three Pandas series from numpyarray. Create three numpy arrays by selecting columns 2,3,4 from the dataset**

*Part 1. Create three Pandas series from numpyarray*

In [40]:
import pandas as pd



#Indexes_100 is a tuple of arrays from np.where()
indexes_100_array = np.array(indexes_100[0])  # Take only the first array, i.e., row indexes

series1 = pd.Series(indexes_100_array)
series2 = pd.Series(indexes_100_array + 10)  # Add 10 to each index
series3 = pd.Series(indexes_100_array * 2)  # Multiply each index by 2


print(series1)

print(series2)

print(series3)

0      11
1      16
2      25
3      28
4      37
5      38
6      42
7      72
8      78
9      79
10     83
11     84
12     87
13    113
14    142
15    157
16    163
dtype: int64
0      21
1      26
2      35
3      38
4      47
5      48
6      52
7      82
8      88
9      89
10     93
11     94
12     97
13    123
14    152
15    167
16    173
dtype: int64
0      22
1      32
2      50
3      56
4      74
5      76
6      84
7     144
8     156
9     158
10    166
11    168
12    174
13    226
14    284
15    314
16    326
dtype: int64


*Part 2: Create three numpy arrays by selecting columns 2,3,4 from the dataset*

In [58]:
import numpy as np

numpy_array2 = data['Pulse']
numpy_array3 = data['Maxpulse']
numpy_array4 = data['Calories']


print(f"Column 2={numpy_array2}\n")

print(f"Column 3={numpy_array3}\n")

print(f"Column 4={numpy_array4}\n")

Column 2=[110 117 103 109 117 102 110 104 109  98 103 100 106 104  98  98 100  90
 103  97 108  -1 130 105 102 100  92 103 100 102  92  90 101  93 107 114
 102 100 100 104  90  -1 100 111 111  99 109 111 108 111 107 123 106 118
 136 121 118 115 153 123 108 110 109 118 110  90 105 107 106 108  97 109
 100  97 114  98 105 110 100 100 159  -1 103 100 100 151 102 100 129  83
 101 107  90  80 150 151  95 152 109  93  95  90  90  90  92  93  90  90
  90 137 102 107 124 100 108 108 116  97 105 103 112  -1 119 107 111  98
  97 109  99 114 104 107 103 106 103 136 117 115 113 141 108  97 100 122
 136 106 107 112 103 110 106 109 109 150  -1 111  97 100 114  80  85  90
  95 100 105 110 115 120 125]

Column 3=[130 145 135 175 148 127 136 134 133 124 147 120 128 132 123 120 120 112
 123 125 131 119 101 132 126 120 118 132 132 129 115 112 124 113 136 140
 127 120 120 129 112 126 122 138 131 119 153 136 129 139 136 146 130 151
 175 146 121 144 172 152 160 137 135 141 130 130 135 130 136 143 129 153
 1

**Q12: Create a new data frame, 'df,' from the pandas series created in Q11**.

In [60]:
# Create a new DataFrame
df = pd.DataFrame({'Series 1': series1, 'Series 2': series2, 'Series 3': series3})
#In this example, a new DataFrame named 'df' is created using the pd.DataFrame()

df.head()

Series 1  Series 2  Series 3
0        11        21        22
1        16        26        32
2        25        35        50
3        28        38        56
4        37        47        74